apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 3
  template:
    metadata:
      name: node
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: <AzureContainerId>/aks-docker-node:v1
        imagePullPolicy: IfNotPresent
        resources: {}
      restartPolicy: Always
        
  selector:
    matchLabels:
      app: node

---

apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node
  ports:
    - port: 3000
  type: LoadBalancer